# Generated by Django 4.0.2 on 2022-03-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
