# Generated by Django 4.0.2 on 2022-03-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(default='', max_length=100, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
