# Generated by Django 4.0.2 on 2022-03-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Imagen'),
        ),
    ]
