# Generated by Django 4.0.2 on 2022-03-06 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_pedido_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Creado el'),
        ),
    ]
