# Generated by Django 4.0.2 on 2022-03-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_pedido_precio_total_alter_product_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.FloatField(default=0, verbose_name='Precio Total'),
            preserve_default=False,
        ),
    ]
