# Generated by Django 4.0.2 on 2022-03-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_product_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='product',
            new_name='producto',
        ),
    ]
